### PR TITLE
(feat): Moves json data to markdown

### PR DESCRIPTION
**Pull request by abhilashlr**
Addresses #12

### CODE REVIEW

**Comment by abhilashlr** [comment]
@kennethlarsen @JennyJudova This PR is now ready for review and has the changes for all 3 models that include features and deprecations.

**Comment by JennyJudova** [comment]
Nice! Runs locally like a charm. And the markdown is definitely tidier than what it was or a large .json

**Comment by kennethlarsen** [comment]
@abhilashlr If you're up for another task we should probably create a blueprint for this :)

**Comment by abhilashlr** [comment]
On it @kennethlarsen 👍 Will bring up something in couple of days.

**Pull request merged**
